### ISSUE TITLE
ctrl+/ comment bug

### ISSUE THREAD

**Issue by beeplin** [seanwash/vscode-vue-components#3]
best vue plugin for vs code ever~! thanks!

one issue: always insert `//` before a line when press `ctrl \`, even in the html/css/coffee... parts.

it would be better to behave like this: 

if current cursor position is in a < script>...< /script> part, insert //;
if in a < script  ... lang="coffee"> ... < /script> part, insert # ;
if in a < style.... < /style> part, insert /\* ... */
otherwise: insert < !-- ... -->

**Comment by seanwash** [comment]
@beeplin Thanks, I'll check in on this!

**Comment by seanwash** [comment]
FYI this looks to be a limitation with code for now.

In the language config file we only have options for one type of line comment and one type of block comment:

```
{
  "comments": {
      // symbol used for single line comment. Remove this entry if your language does not support line comments
      "lineComment": "//",
      // symbols used for start and end a block comment. Remove this entry if your language does not support block comments
      "blockComment": [ "/*", "*/" ]
  }
}
```

**Comment by beeplin** [comment]
got it. seems we have to separate vue files into vue\js\css files to get better language.support.

**Comment by seanwash** [comment]
@beeplin Yeah I think you're right. I'll keep looking through the code repo to see if I can't find anything useful there – there are a ton of open issues so I'm sure that there's one that we can add our voices to.

**Comment by seanwash** [comment]
Here's a relevant open issue https://github.com/Microsoft/vscode/issues/8928
